# Generated by Django 4.1.5 on 2023-01-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_user',
            new_name='watchlist',
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
