# Generated by Django 4.1.5 on 2023-01-07 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0005_rename_review_user_review_watchlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='watchlist',
        ),
    ]
